@echo off
cd /d "%~dp0"
:: Creating virtual environment...
echo Creating virtual environment...
python -m venv venv
:: Activating virtual environment...
echo Activating virtual environment...
call venv\Scripts\activate.bat
:: Starting proxy...
echo Starting proxy...
python proxy_start_v2.py
timeout /t 5 /nobreak
exit
